alias builtcode_test='cd ~/workspace/rails_app/builtcode_test'
alias run='docker-compose run --rm web bundle exec'
alias up='docker-compose up'
alias stop='docker-compose stop'
alias down='docker-compose down'
alias bundle_install='docker-compose run --rm web bundle install'
alias remove_pid='sudo rm ~/workspace/rails_app/builtcode_test/tmp/pids/server.pid'
