services:
  web:
    build: .
    command: bundle exec rails s -b 0.0.0.0
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    volumes:
      - '.:/workspace/rails_app/builtcode_test'
        
  box:
    image: busybox
    volumes:
      - /workspace/rails_app/builtcode_test/box